name = "fleet-app"
compatibility_date = "2024-02-04"

# Durable Objects configuration
[durable_objects]
bindings = [
  { name = "FLEET_DO", class_name = "FleetDurableObject", script_name = "do" }
]

[[migrations]]
tag = "v1"
new_classes = ["FleetDurableObject"]